<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert(array(
            [ 'id'=>'1','name'=>'Angoda','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'2','name'=>'Athurugiriya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'3','name'=>'Avissawella','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'4','name'=>'Battaramulla','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'5','name'=>'Boralesgamuwa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'6','name'=>'Colombo 1','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'7','name'=>'Colombo 10','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'8','name'=>'Colombo 11','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'9','name'=>'Colombo 12','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'10','name'=>'Colombo 13','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'11','name'=>'Colombo 14','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'12','name'=>'Colombo 15','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'13','name'=>'Colombo 2','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'14','name'=>'Colombo 3','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'15','name'=>'Colombo 4','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'16','name'=>'Colombo 5','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'17','name'=>'Colombo 6','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'18','name'=>'Colombo 7','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'19','name'=>'Colombo 8','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'20','name'=>'Colombo 9','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'21','name'=>'Dehiwala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'22','name'=>'Hanwella','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'23','name'=>'Homagama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'24','name'=>'Kaduwela','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'25','name'=>'Kesbewa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'26','name'=>'Kohuwala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'27','name'=>'Kolonnawa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'28','name'=>'Kottawa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'29','name'=>'Kotte','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'30','name'=>'Maharagama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'31','name'=>'Malabe','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'32','name'=>'Moratuwa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'33','name'=>'Mount Laviniya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'34','name'=>'Nawala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'35','name'=>'Nugegoda','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'36','name'=>'Padukka','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'37','name'=>'Pannipitiya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'38','name'=>'Piliyandala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'39','name'=>'Ratmalana','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'40','name'=>'Talawatugoda','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'41','name'=>'Wellampitiya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'42','name'=>'Akurana','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'43','name'=>'Ampitiya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'44','name'=>'Digana','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'45','name'=>'Galagedara','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'46','name'=>'Gampola','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'47','name'=>'Gelioya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'48','name'=>'Kadugannawa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'49','name'=>'Kandy','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'50','name'=>'Katugastota','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'51','name'=>'Kundasale','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'52','name'=>'Madawala Bazaar','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'53','name'=>'Nawalapitiya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'54','name'=>'Peradeniya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'55','name'=>'Pilimatalawa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'56','name'=>'Wattegama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'57','name'=>'Ahangama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'58','name'=>'Ambalangoda','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'59','name'=>'Baddegama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'60','name'=>'Batapola','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'61','name'=>'Bentota','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'62','name'=>'Elpitiya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'63','name'=>'Galle','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'64','name'=>'Hikkaduwa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'65','name'=>'Karapitiya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'66','name'=>'Akkarepattu','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'67','name'=>'Ampara','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'68','name'=>'Kalmunai','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'69','name'=>'Sinthamaruthu','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'70','name'=>'Anuradhapura','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'71','name'=>'Eppawala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'72','name'=>'Galenbindunuwewa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'73','name'=>'Galnewa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'74','name'=>'Habarana','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'75','name'=>'Kekirawa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'76','name'=>'Medawachchiya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'77','name'=>'Mihintale','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'78','name'=>'Nochchiyagama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'79','name'=>'Talawa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'80','name'=>'Tambuttegama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'81','name'=>'Badulla','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'82','name'=>'Bandarawela','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'83','name'=>'Diyatalawa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'84','name'=>'Ella','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'85','name'=>'Hali Ela','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'86','name'=>'Haputale','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'87','name'=>'Mahiyanganaya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'88','name'=>'Passara','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'89','name'=>'Welimada','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'90','name'=>'Batticaloa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'91','name'=>'Delgoda','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'92','name'=>'Divulapitiya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'93','name'=>'Gampaha','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'94','name'=>'Ganemulla','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'95','name'=>'Ja-Ela','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'96','name'=>'Kadawatha','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'97','name'=>'Kandana','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'98','name'=>'Katunayake','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'99','name'=>'Kelaniya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'100','name'=>'Kiribathgoda','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'101','name'=>'Minuwangoda','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'102','name'=>'Mirigama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'103','name'=>'Negombo','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'104','name'=>'Nittambuwa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'105','name'=>'Ragama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'106','name'=>'Veyangoda','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'107','name'=>'Wattala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'108','name'=>'Ambalantota','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'109','name'=>'Beliatta','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'110','name'=>'Hambantota','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'111','name'=>'Tangalla','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'112','name'=>'Tissamaharama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'113','name'=>'Chavakachcheri','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'114','name'=>'Jaffna','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'115','name'=>'Nallur','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'116','name'=>'Alutgama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'117','name'=>'Bandaragama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'118','name'=>'Beruwala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'119','name'=>'Horana','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'120','name'=>'Ingiriya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'121','name'=>'Kalutara','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'122','name'=>'Matugama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'123','name'=>'Panadura','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'124','name'=>'Wadduwa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'125','name'=>'Dehiowita','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'126','name'=>'Deraniyagala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'127','name'=>'Galigamuwa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'128','name'=>'Kegalle','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'129','name'=>'Kitulgala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'130','name'=>'Mawanella','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'131','name'=>'Rambukkana','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'132','name'=>'Ruwanwella','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'133','name'=>'Warakapola','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'134','name'=>'Yatiyantota','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'135','name'=>'Kilinochchi','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'136','name'=>'Alawwa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'137','name'=>'Bingiriya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'138','name'=>'Galgamuwa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'139','name'=>'Giriulla','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'140','name'=>'Httipola','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'141','name'=>'Ibbagamuwa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'142','name'=>'Kuliyapitiya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'143','name'=>'Kurunegala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'144','name'=>'Mawathagama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'145','name'=>'Narammala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'146','name'=>'Nikaweratiya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'147','name'=>'Pannala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'148','name'=>'Polgahawela','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'149','name'=>'Wariyapola','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'150','name'=>'Mannar','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'151','name'=>'Dambulla','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'152','name'=>'Galewela','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'153','name'=>'Matale','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'154','name'=>'Palapathwela','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'155','name'=>'Rattota','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'156','name'=>'Sigiriya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'157','name'=>'Ukuwela','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'158','name'=>'Yatawatta','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'159','name'=>'Akuressa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'160','name'=>'Deniyaya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'161','name'=>'Dikwella','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'162','name'=>'Hakmana','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'163','name'=>'Kamburugamuwa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'164','name'=>'Kamburupitiya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'165','name'=>'Kekanadurra','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'166','name'=>'Matara','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'167','name'=>'Weligama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'168','name'=>'Bibile','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'169','name'=>'Buttala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'170','name'=>'Kataragama','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'171','name'=>'Moneragala','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'172','name'=>'Wellawaya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'173','name'=>'Mullativu','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'174','name'=>'Ginigathena','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'175','name'=>'Hatton','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'176','name'=>'Madulla','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'177','name'=>'Nuwara Eliya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'178','name'=>'Hingurakgoda','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'179','name'=>'Kaduruwela','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'180','name'=>'Medirigiriya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'181','name'=>'Polonnaruwa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'182','name'=>'Chilaw','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'183','name'=>'Dankotuwa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'184','name'=>'Marawila','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'185','name'=>'Nattandiya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'186','name'=>'Puttalam','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'187','name'=>'Wennappuwa','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'188','name'=>'Balangoda','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'189','name'=>'Eheliyagoda','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'190','name'=>'Embilipitiya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'191','name'=>'Kuruwita','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'192','name'=>'Pelmadulla','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'193','name'=>'Ratnapura','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'194','name'=>'Trincomalee','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'195','name'=>'Kinniya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
[ 'id'=>'196','name'=>'Vavuniya','created_at' => Carbon::now(),'updated_at' => Carbon::now() ],
        ));
    }
}
